trigger:
- main
- dev

pr:
- '*'

pool:
  name: 'my-pool' # Replace with your agent pool name

variables:
  buildConfiguration: 'Release'
  sonarCloudToken: '5b30826e4d335cd54e451c52006b6b5f965ca4cf'  # Replace with the SonarCloud token you generated

stages:
- stage: BuildAndAnalyze
  displayName: 'Build and Analyze'
  jobs:
  - job: BuildAndAnalyze
    displayName: 'Build and Analyze Job'
    pool:
      name: 'my-pool' # Replace with your agent pool name

    steps:
    - checkout: self

    - script: |
        # Use the full path to the executable
        $HOME/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.organization=ronakthecloud \
          -Dsonar.projectKey=ronakthecloud_repos2 \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io
      displayName: 'Run SonarCloud Analysis'

- stage: Deploy
  displayName: 'Deploy to Environment'
  dependsOn: BuildAndAnalyze
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    pool:
      name: 'my-pool' # Replace with your agent pool name

    steps:
    - checkout: self

    - script: echo 'Deploying...'
      displayName: 'Deploy'
      # Add your deployment steps here, for example, copying files to a web server
